name: aurora_viking_app
description: "Aurora Viking - Your guide to the Northern Lights in Iceland"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: ^1.0.6

  # Charts and Data Visualization
  fl_chart: ^0.66.0

  # HTTP for NOAA API calls
  http: ^1.1.0

  # Basic utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true