name: aurora_viking_app
description: "Aurora Viking - Aurora Forecast & Community App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI & Charts
  fl_chart: ^0.69.0
  cupertino_icons: ^1.0.8

  # HTTP & Networking
  http: ^1.2.2
  dio: ^5.7.0

  # Firebase Core Services
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.3
  firebase_storage: ^12.3.2
  firebase_analytics: ^11.3.3
  firebase_messaging: ^15.1.3

  # Location & Maps
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  location: ^7.0.0

  # Camera & Media
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  image: ^4.2.0

  # Permissions
  permission_handler: ^11.3.1

  # Notifications
  flutter_local_notifications: ^18.0.1

  # Storage & Files
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  sqflite: ^2.3.3+2

  # E-commerce & Payments
  flutter_stripe: ^11.1.0

  # Utilities
  intl: ^0.19.0
  uuid: ^4.5.1
  connectivity_plus: ^6.0.5
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  url_launcher: ^6.3.1
  share_plus: ^10.0.2

  # Animations & UI
  lottie: ^3.1.2
  flutter_staggered_animations: ^1.1.1

  # Environment & Config
  flutter_dotenv: ^5.1.0

  # JSON & Data
  json_annotation: ^4.9.0

  # PDF & Printing
  printing: ^5.13.2
  pdf: ^3.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

  # App Icon & Splash
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#0a0f1c"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# Splash Screen Configuration
flutter_native_splash:
  color: "#0a0f1c"
  image: "assets/images/splash_logo.png"
  android_12:
    color: "#0a0f1c"
    image: "assets/images/splash_logo.png"

flutter:
  uses-material-design: true

  # Assets will be added as you create them
  # assets:
  #   - assets/images/
  #   - assets/icons/
  #   - assets/animations/
  #   - .env

  # Custom fonts will be added later
  # fonts:
  #   - family: Orbitron
  #     fonts:
  #       - asset: assets/fonts/Orbitron-Regular.ttf
  #       - asset: assets/fonts/Orbitron-Bold.ttf
  #         weight: 700