// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC_Kazxx-IdcIOCGdKANwg5vvyd9ekVf8',
    appId: '1:1099021548072:web:b334ae0f5754a03600d31d',
    messagingSenderId: '1099021548072',
    projectId: 'aurora-viking-app',
    authDomain: 'aurora-viking-app.firebaseapp.com',
    storageBucket: 'aurora-viking-app.firebasestorage.app',
    measurementId: 'G-RK53TKBGM5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArCh7e0p46r-ltBRuV08vYxha0eo7DOZo',
    appId: '1:1099021548072:android:abdcb84b6defa64100d31d',
    messagingSenderId: '1099021548072',
    projectId: 'aurora-viking-app',
    storageBucket: 'aurora-viking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMDM4vX4YqH9KGWC1Pwgy32nQ61paCrYU',
    appId: '1:1099021548072:ios:db9254655858cf4a00d31d',
    messagingSenderId: '1099021548072',
    projectId: 'aurora-viking-app',
    storageBucket: 'aurora-viking-app.firebasestorage.app',
    iosBundleId: 'com.example.auroraVikingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMDM4vX4YqH9KGWC1Pwgy32nQ61paCrYU',
    appId: '1:1099021548072:ios:db9254655858cf4a00d31d',
    messagingSenderId: '1099021548072',
    projectId: 'aurora-viking-app',
    storageBucket: 'aurora-viking-app.firebasestorage.app',
    iosBundleId: 'com.example.auroraVikingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC_Kazxx-IdcIOCGdKANwg5vvyd9ekVf8',
    appId: '1:1099021548072:web:f7c4a0e4485cf1e500d31d',
    messagingSenderId: '1099021548072',
    projectId: 'aurora-viking-app',
    authDomain: 'aurora-viking-app.firebaseapp.com',
    storageBucket: 'aurora-viking-app.firebasestorage.app',
    measurementId: 'G-JWH4VJTVVV',
  );
}
